@extends('layouts.absensi')
@section('title','Laporan HR - PT. INTI')
@section('content')
<div class="flex flex-col gap-space-lg">
  <div class="flex flex-col md:flex-row md:items-end md:justify-between gap-space-md"><div><span class="text-[11px] font-semibold text-on-surface-variant uppercase tracking-wider">REPORTING</span><h1 class="font-headline-lg text-primary mt-1">Laporan HR</h1><p class="text-on-surface-variant mt-1">Rekap presensi dan lembur resmi yang telah diverifikasi HR.</p></div><div class="flex gap-2"><a href="{{ route('reports.excel', request()->query()) }}" class="rounded-lg bg-secondary text-white px-4 py-2 text-sm font-semibold">Excel</a><a href="{{ route('reports.pdf', request()->query()) }}" class="rounded-lg bg-primary-container text-white px-4 py-2 text-sm font-semibold">PDF</a></div></div>
  <form class="bg-surface-container-lowest rounded-2xl p-space-lg shadow-sm flex flex-wrap gap-3 items-end"><div><label class="text-xs text-on-surface-variant">Bulan</label><select name="month" class="block rounded-lg border-outline-variant bg-surface-container-low mt-1">@foreach(range(1,12) as $m)<option value="{{ $m }}" @selected($month === $m)>{{ \Carbon\Carbon::create()->month($m)->translatedFormat('F') }}</option>@endforeach</select></div><div><label class="text-xs text-on-surface-variant">Tahun</label><input name="year" value="{{ $year }}" class="block w-28 rounded-lg border-outline-variant bg-surface-container-low mt-1"></div><div><label class="text-xs text-on-surface-variant">Divisi</label><select name="division_id" class="block min-w-52 rounded-lg border-outline-variant bg-surface-container-low mt-1"><option value="">Semua Divisi</option>@foreach($divisions as $division)<option value="{{ $division->id }}" @selected($divisionId === $division->id)>{{ $division->nama }}</option>@endforeach</select></div><button class="rounded-lg bg-primary-container text-white px-5 py-2 font-semibold">Tampilkan</button></form>
  <div class="grid grid-cols-2 md:grid-cols-4 gap-4">@foreach([['Karyawan',$summary['employee_count']],['Kehadiran',$summary['attendance_avg'].'%'],['Telat',$summary['late_minutes'].' menit'],['OT Resmi',$formatMinutes($summary['official_ot_minutes'] ?? 0)]] as $card)<div class="bg-surface-container-lowest rounded-2xl p-space-lg shadow-sm"><div class="text-xs text-on-surface-variant">{{ $card[0] }}</div><div class="text-2xl font-bold text-primary mt-2">{{ $card[1] }}</div></div>@endforeach</div>
  <div class="bg-surface-container-lowest rounded-2xl shadow-sm overflow-hidden"><div class="p-space-lg border-b border-outline-variant/40"><h2 class="font-headline-md text-primary">Rekap Per Karyawan · {{ $monthLabel }}</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[980px] text-left"><thead class="bg-surface-container-low text-xs uppercase text-on-surface-variant"><tr><th class="p-3">NIPEG</th><th class="p-3">Nama</th><th class="p-3">Divisi</th><th class="p-3">Hadir</th><th class="p-3">Telat</th><th class="p-3">Menit</th><th class="p-3">Alpha</th><th class="p-3">Kehadiran</th><th class="p-3">OT Resmi</th></tr></thead><tbody class="divide-y divide-surface-container-low">@forelse($rows as $row)<tr><td class="p-3 font-mono text-xs">{{ $row['nipeg'] }}</td><td class="p-3 font-semibold">{{ $row['nama'] }}</td><td class="p-3">{{ $row['divisi'] }}</td><td class="p-3">{{ $row['hadir'] }}</td><td class="p-3">{{ $row['telat_hari'] }}</td><td class="p-3">{{ $row['menit_telat'] }}</td><td class="p-3">{{ $row['alpha'] }}</td><td class="p-3">{{ number_format($row['persen_kehadiran'],1) }}%</td><td class="p-3 font-semibold text-secondary">{{ $formatMinutes($row['official_ot_minutes']) }}</td></tr>@empty<tr><td colspan="9" class="p-8 text-center text-on-surface-variant">Belum ada data untuk periode ini.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
